### ISSUE TITLE
SEO optimization

### ISSUE THREAD

**Issue by brainrepo** [brainrepo/gitbar-2023#1]
- L'homepage deve esporre i tag meta presenti sul vecchio sito
- La pagina episodio deve mostrare gli stessi tag meta della pagina episodio del vecchio tipo, naturalmente mostrando le info dell'episodio visualizzato nella pagina
- Le pagine speaker avere gli stessi meta tags

**Comment by LucaRainone** [comment]
> Le pagine speaker avere gli stessi meta tags

intendi gli stessi metatags della home? Non sarebbe meglio metatags peculiari?

**Comment by brainrepo** [comment]
Intendevo la struttura, si hai ragione avrei dovuto scrivere meglio la issue
