### ISSUE TITLE
Pagina donazioni

### ISSUE THREAD

**Issue by brainrepo** [brainrepo/gitbar-2023#2]
- seguendo il layout della pagina speaker implementare una pagina supportaci con url /support.
- I contenuti sono quelli presenti nella pagina donazioni del vecchio sito

**Comment by emanuelegurini** [comment]
Hi @brainrepo, can i grab this issue?

**Comment by brainrepo** [comment]
@EmanueleGurini  Yes sure! Your help is appreciated!

**Comment by brainrepo** [comment]
Ciao @EmanueleGurini , sei ancora interessato in questa issue?

**Comment by emanuelegurini** [comment]
@brainrepo Ciao Mauro, yes, ci sto lavorando a sprazzi e bocconi, ma ci sto lavorando. La settimana prossima dovrebbe essere fuori.

**Comment by brainrepo** [comment]
Grazie di cuore
