### ISSUE TITLE
Pagina singolo episodio perde layout in versione mobile

### ISSUE THREAD

**Issue by markoceri** [brainrepo/gitbar-2023#44]
Nella pagina dedicata alla visualizzazione del singolo episodio il layout viene perso in versione mobile.

![image](https://user-images.githubusercontent.com/16639103/206032459-05a0778d-89b2-4fa3-8154-54bcb7c446f9.png)

**Comment by emanuelegurini** [comment]
@markoceri, has this problem been solved?

**Comment by markoceri** [comment]
@EmanueleGurini I have not fixed yet. I have seen your fix now and it works great in mobile version. :thumbsup:

I think that putting a _break-words_ class can fix even cases of very long words in the title (like _404answernotfound_) but, I'm not so good with frontend and I just guessing. :smiley:

Thanks for your fix.

**Comment by emanuelegurini** [comment]
> @EmanueleGurini I have not fixed yet. I have seen your fix now and it works great in mobile version. 👍
> 
> I think that putting a _break-words_ class can fix even cases of very long words in the title (like _404answernotfound_) but, I'm not so good with frontend and I just guessing. 😃
> 
> Thanks for your fix.

Great, and thanks for the advice, I'll try to add break-words tomorrow
