### ISSUE TITLE
Orario di pubblicazione errato

### ISSUE THREAD

**Issue by Takeno** [brainrepo/gitbar-2023#47]
L'orario di pubblicazione delle puntate è sbagliato, riporta due volte l'ora anziché i minuti.

<img width="507" alt="immagine" src="https://user-images.githubusercontent.com/1499063/206449899-f36603da-6fb2-4d0c-9954-08c6085130d8.png">

**Comment by markoceri** [comment]
Ciao @Takeno, posso fixarla io?

**Comment by Takeno** [comment]
@markoceri per me ok :)
