### ISSUE TITLE
Mixed content detected

### ISSUE THREAD

**Issue by brainrepo** [brainrepo/gitbar-2023#7]
Solve the mixed content detected error

--- 

Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection.

**DETAILS**
In index.html:

link http://localhost:3000/

**Comment by LucaRainone** [comment]
this was caused by canonical url autofilled by astro taking the current url. Fixed by https://github.com/brainrepo/gitbar-2023/pull/11 (making explicit canonical url with full url)
