### ISSUE TITLE
Episode list

### ISSUE THREAD

**Issue by brainrepo** [brainrepo/gitbar-2023#8]
Set higher z-index for episode card on the onHover state

![Screenshot 2022-10-28 at 17 29 03](https://user-images.githubusercontent.com/1851362/198675847-acabed0f-9c63-42b3-b28c-3e2779b7eea1.png)

**Comment by siddhesh-desai** [comment]
Hello @brainrepo, would like to work on this. Please assign it to me.

**Comment by brainrepo** [comment]
Yes thank you at mil

**Comment by brainrepo** [comment]
@siddhesh-desai are you still interested?

**Comment by siddhesh-desai** [comment]
> @siddhesh-desai are you still interested?

Yes

**Comment by brainrepo** [comment]
Thank you
